config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new]

  get '/register', to: 'chefs#new'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { minimum: 3, maximum: 40 }
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_many :recipes
  has_many :likes

  has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :chef
  belongs_to :recipe

  scope :liked, -> (recipe) { where(recipe: recipe, like: true) }
  scope :disliked, -> (recipe) { where(recipe: recipe, like: false) }

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  validates :chef_id, presence: true
  validate :picture_size

  mount_uploader :picture, PictureUploader

  belongs_to :chef
  has_many :likes

  def liked
    Like.liked(self).count
  end

  def disliked
    Like.disliked(self).count
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add :picture, 'should be less than 5 MB'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id].present?
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = 'Only logged in users can perform that action.'
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :confirm_user, only: [:edit, :update]

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new chef_params

    if @chef.save
      session[:chef_id] = @chef.id
      flash[:success] = 'Your account has been successfully created.'
      redirect_to @chef
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @chef.update chef_params
      flash[:success] = 'Your profile has been updated successfully.'
      redirect_to @chef
    else
      render :edit
    end
  end

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3).order(updated_at: :desc)
  end

  def destroy
  end

  private

  def chef_params
    params.require(:chef).permit :name, :email, :password
  end

  def set_user
    @chef = Chef.find params[:id]
  end

  def confirm_user
    if current_user != @chef
      flash[:danger] = "You can't edit other users profiles."
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index]
  before_action :confirm_user, only: [:edit, :update]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4).order(updated_at: :desc)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new recipe_params
    @recipe.chef = current_user

    if @recipe.save
      flash[:success] = 'Your recipe was created.'
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update recipe_params
      flash[:success] = 'Your recipe was updated.'
      redirect_to @recipe
    else
      render :edit
    end
  end

  def like
    like = Like.find_or_create_by(chef: current_user, recipe: @recipe)

    like.update(like: params[:like])
    redirect_to :back
  end

  private

  def recipe_params
    params.require(:recipe).permit :name, :summary, :description, :picture
  end

  def set_recipe
    @recipe = Recipe.find params[:id]
  end

  def confirm_user
    if current_user != @recipe.chef
      flash[:danger] = "You can't edit other users recipes."
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    chef = Chef.find_by_email params[:email]

    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = 'Successfully logged in.'
      redirect_to recipes_path
    else
      flash.now[:danger] = 'Your email and/or password does not match.'
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = 'Logged out.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest chef.email.downcase
    size = options[:size]
    url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    image_tag(url, alt: chef.name, class: 'gravatar')
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', object: @chef %>

<div class="row">

  <div class="well col-md-8 col-md-offset-2">

    <%= form_for @chef do |f| %>

      <div class="form-group">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, class: 'form-label' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <%= f.submit (@chef.new_record? ? 'Register' : 'Edit'), class: 'btn btn-success form-control' %>

    <% end %>

  </div>

</div>

app/views/chefs/edit.html.erb
<%= render 'shared/header', title: 'Edit Profile' %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<main>
  <%= render 'shared/header', title: 'Chefs' %>

  <div class="text-center">
    <%= will_paginate %>
  </div>

  <%= div_for @chefs, class: 'row' do |chef| %>
    <div class="col-md-4 col-md-offset-4 text-center">
      <%= link_to gravatar_for(chef, size: 200), chef %>
      <h4><%= chef.name %></h4>
    </div>
  <% end %>

  <%= render 'shared/fab', title: 'Add a Chef', path: register_path, icon: 'glyphicon glyphicon-plus' %>
</main>

app/views/chefs/new.html.erb
<%= render 'shared/header', title: 'Register' %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<main>
  <article>
    <%= render 'shared/header', title: @chef.name %>

    <div class="row">
      <div class="col-md-4 col-md-offset-4 text-center">
        <%= gravatar_for @chef, size: 200 %>
        <hr>
      </div>
    </div>

    <div class="text-center">
      <%= will_paginate @recipes %>
    </div>

    <section>
      <%= div_for @recipes, class: 'row' do |recipe| %>
        <div class="col-lg-10 col-lg-offset-1 recipe well">
          <h4>
            <%= link_to recipe.name, recipe_path(recipe) %>
            <%= image_tag recipe.picture.url, size: '200x150', class: 'preview pull-right' if recipe.picture? %>
          </h4>

          <%= simple_format recipe.summary %>

          <div style="clear: right"></div>

          <span class="pull-right help-block">

            <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                  <i class="glyphicon glyphicon-thumbs-up"></i>
                <% end %>
            <%= recipe.liked %>
            &nbsp;
            <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                  <i class="glyphicon glyphicon-thumbs-down"></i>
                <% end %>
            <%= recipe.disliked %>
          </span>
        </div>
      <% end %>
    </section>
  </article>

  <% if current_user == @chef %>
    <%= render 'shared/fab', title: 'Edit', path: edit_chef_path, icon: 'glyphicon glyphicon-edit' %>
  <% end %>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Cookbook 2015</p>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>

<div class="row">

  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |type, message| %>

    <div class="alert alert-<%= type %>">

      <%= message %>
      <a class="close" data-dismiss="alert">&#215;</a>

    </div>

    <% end %>
  </div>

</div>

<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation Bar -->
<nav class="navbar navbar-fixed-top navbar-default">

  <div class="container">

    <div class="navbar-header">

      <!-- For mobile display -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#nav-content">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Cookbook', root_path, class: 'navbar-brand' %>
    </div>

    <div id="nav-content" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li <%= 'class=active' if params[:controller] == 'recipes' %>><%= link_to 'Recipes', recipes_path %></li>
        <li <%= 'class=active' if params[:controller] == 'chefs' %>><%= link_to 'Chefs', chefs_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li class="divider"></li>
              <li><%= link_to 'Log Out', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Cookbook</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

  <%= render 'layouts/navigation' %>

  <div class="container">

    <%= render 'layouts/messages' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </div>

  </body>

</html>

app/views/pages/home.html.erb
<div class="center jumbotron">

  <h1>Welcome to Cookbook</h1>

  <p class="lead">
    This is the home page for the "professional" RoR course on Udemy.
  </p>

  <%= link_to 'Sign up now!', register_path, class: 'btn btn-lg btn-primary' %>

</div>

<div class="row">

  <div class="col-lg-4">

    <h3>
      View Recipes as Guest User
    </h3>

    <p>Browse and view recipes as a guest and sign up later.</p>

    <p><%= link_to 'Browse Recipe Listings', recipes_path, class: 'btn btn-warning btn-small' %></p>
  </div>

  <div class="col-lg-4">

    <h3>
      View Recipes as Guest User
    </h3>

    <p>Browse and view recipes as a guest and sign up later.</p>

    <p><%= link_to 'Browse Recipe Listings', '', class: 'btn btn-warning btn-small' %></p>
  </div>

  <div class="col-lg-4">

    <h3>
      View Recipes as Guest User
    </h3>

    <p>Browse and view recipes as a guest and sign up later.</p>

    <p><%= link_to 'Browse Recipe Listings', '', class: 'btn btn-warning btn-small' %></p>
  </div>

</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', object: @recipe %>

<div class="row">

  <div class="well col-md-8 col-md-offset-2">

    <%= form_for @recipe, html: { multipart: true } do |f| %>

      <div class="form-group">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :summary, class: 'form-label' %>
        <%= f.text_field :summary, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description, class: 'form-label' %>
        <%= f.text_area :description, class: 'form-control', rows: 10 %>
      </div>

      <div class="form-group">
        <%= f.label :picture, class: 'form-label' %>
        <span class="picture"><%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %></span>
      </div>

      <%= f.submit (@recipe.new_record? ? 'Create' : 'Edit'), class: 'btn btn-success form-control' %>

    <% end %>

  </div>

</div>

app/views/recipes/edit.html.erb
<main>

  <%= render 'shared/header', title: "Edit #{@recipe.name}" %>

  <%= render 'form' %>

</main>

app/views/recipes/index.html.erb
<main>

  <%= render 'shared/header', title: 'Recipes' %>

  <div class="text-center">
    <%= will_paginate %>
  </div>

  <%= div_for @recipes, class: 'row article' do |recipe| %>

    <div class="col-md-2">

      <%= div_for recipe.chef, class: 'chef-info text-center' do %>

        <%= gravatar_for recipe.chef, size: 100 %>
        <h5><%= recipe.chef.name %></h5>

      <% end %>

    </div>

    <%= div_for recipe, class: 'col-lg-10 recipe well' do %>

      <h4>
        <%= link_to recipe.name, recipe_path(recipe) %>
        <%= image_tag recipe.picture.url, size: '200x150', class: 'preview pull-right' if recipe.picture? %>
      </h4>
      <%= simple_format recipe.summary %>
      <div style="clear: right"></div>

      <% if logged_in? %>
        <span class="pull-right help-block">

          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i>
              <% end %>
          <%= recipe.liked %>
          &nbsp;
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>
              <% end %>
          <%= recipe.disliked %>

        </span>
      <% end %>

    <% end %>

  <% end %>

  <div class="text-center">
    <%= will_paginate %>
  </div>

  <% if logged_in? %>
    <%= render 'shared/fab', title: 'Add a Recipe', path: new_recipe_path, icon: 'glyphicon glyphicon-plus' %>
  <% end %>

</main>

app/views/recipes/new.html.erb
<main>

  <%= render 'shared/header', title: 'Create a Recipe' %>

  <%= render 'form' %>

</main>

app/views/recipes/show.html.erb
<main>

  <article>

    <%= render 'shared/header', title: @recipe.name %>

    <div class="row">

      <!-- User details to the right of the recipe information. -->
      <div class="col-md-4 pull-right text-center">

        <%= link_to gravatar_for(@recipe.chef, size: 200), @recipe.chef %>
        <h5><%= @recipe.chef.name %></h5>

      </div>

      <div class="col-md-8">

        <p class="lead"><%= @recipe.summary %></p>
        <!-- The column class is needed to fix the padding for the like & dislike buttons. -->
        <div class="col-md-12 well">

          <p><strong>Steps</strong></p>
          <%= simple_format @recipe.description %>

          <div style="clear: right;"></div>

          <% if logged_in? %>
            <div class="pull-right">

              <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i>
              <% end %>
              <%= @recipe.liked %>
              &nbsp;
              <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>
              <% end %>
              <%= @recipe.disliked %>

            </div>
          <% end %>

        </div>

      </div>

    </div>

    <!-- Edit Button -->
    <% if current_user == @recipe.chef && logged_in? %>
      <%= render 'shared/fab', title: 'Edit', path: edit_recipe_path, icon: 'glyphicon glyphicon-edit' %>
    <% end %>

  </article>

</main>

app/views/shared/_errors.html.erb
<!-- Object is provided by the call to render() -->
<% if object.errors.any? %>

  <div class="row">

    <div class="alert alert-danger col-md-8 col-md-offset-2">

      <h5><strong>Please correct the following errors:</strong></h5>

      <ul>

        <% object.errors.full_messages.each do |error| %>

          <li><%= error %></li>

        <% end %>

      </ul>

    </div>

  </div>

<% end %>

app/views/shared/_fab.html.erb
<div id="fab">

  <label class="text-capitalize"><%= title %></label>
  <%= link_to path, class: 'btn btn-primary', alt: title do %>

    <i class="<%= icon %>"></i>

  <% end %>

</div>

app/views/shared/_header.html.erb
<header>

  <h1 class="text-center"><%= title %></h1>
  <hr>

</header>